// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfkytpknqheplkzuwurl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxma3l0cGtucWhlcGxrenV3dXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODIyODcsImV4cCI6MjA3MDQ1ODI4N30.vmG5QY8i6Rr7v2i7MgX3ar0Aj-w97tVDW0lzE_T6QSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});